name: Deploy to Amazon ECR

on:
  workflow_run:
    workflows:
        - "Run Tests"
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: 'us-east-1'
  ECR_REPOSITORY: 'dream'

jobs:
  determine-tag:
    name: Determine Docker Image Tag
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
      - name: Set Image Tag
        id: set-tag
        run: |
          echo ::set-output name=image-tag::${{ github.event_name == 'pull_request' ? 'latest': github.sha }}

  build-and-deploy:
    name: Deploy
    needs: determine-tag
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set env BRANCH
        id: set-env-branch
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

#      - name: Set env IMAGE_TAG
#        id: set-env-image-tag
#        run: |
#          if $BRANCH == 'main'; then
#              echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"
#          else
#              echo "IMAGE_TAG=${{ github.sha }}" >> "$GITHUB_ENV"
#          fi

      - name: Build Tag & Push to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ needs.determine-tag.outputs.image-tag }}
        run: |
          docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT