# This is not really needed for this project as I'm already pushing to ECR
# But I'm keeping it here for future reference and use from DockerHub if needed.

name: Train models and Push new Docker image

on:
  workflow_run:
    workflows:
      - "Run Tests"
    types:
      - completed

env:
  DOCKERHUB_REPO_NAME: 'dream'

jobs:
  train-build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/dream

      - name: Train models and Push new Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
